((nil . ((c-default-style "linux")
         (indent-tabs-mode . nil)
         (c-tab-always-indent . t)
         (c-basic-offset . 4)
         (c-hanging-braces-alist . (
                    (brace-list-open)
                    (brace-list-close)
                    (block-close . c-snug-do-while)
                    (substatement-open before after)))
         (fill-column . 80)
         (subdirs . nil))))
